image: mia3/gitlab-ci:7.4

stages:
  - deploy

before_script:
  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > private_key
  - chmod 600 private_key
  - ssh-add private_key
  - rm private_key
  - ssh-keyscan -p 22 'typo3.mia3.com' >> ~/.ssh/known_hosts

deploy_prod:
  stage: deploy
  script:
    - cat /etc/resolv.conf
    - make production/deploy
  only:
    - main
