image: mia3/gitlab-ci

before_script:
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > private_key
    - chmod 600 private_key
    - ssh-add private_key
    - rm private_key
    - ssh-keyscan -p 22 'typo3.template.mia3.com' >> ~/.ssh/known_hosts
    - ssh-keyscan -p 30001 'gitlab.mia3.com' >> ~/.ssh/known_hosts

stages:
    - production

cache:
    paths:
        - node_modules/
        - vendor/

production:
  stage: production
  script:
    - make install
    - make build/production
  environment: production
  when: manual
  only:
    - 2-update-typo3-base

#tests:
#    stage: test
#    script:
#        - yarn install
#        - yarn run unit